trigger:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    dotnet pack src/Artifacts/Artifacts.csproj \
      --include-symbols \
      --output $(build.artifactStagingDirectory)
  displayName: Create NuGet Package

- task: PublishBuildArtifacts@1
