trigger:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: gittools.gitversion-netcore-preview.gitversion-netcore-task.GitVersionNetCore@4
  displayName: Determine Semantic Version

- script: |  
    echo ##vso[build.updatebuildnumber]$AssemblySemVer
  displayName: Set BuildNumber

- script: |
    dotnet publish src/Artifacts/Artifacts.csproj \
      --output $(build.artifactStagingDirectory)
  displayName: dotnet publish

- task: PublishBuildArtifacts@1
