trigger:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    dotnet pack -c release --include-symbols -o $(build.artifactStagingDirectory) src/Artifacts/Artifacts.csproj
  displayName: Create a NuGet Package

- task: PublishBuildArtifacts@1