pr:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    dotnet test ./tests/Artifacts.Tests/Artifacts.Tests.csproj --logger trx
  displayName: Run Unit Tests

- task: PublishTestResults@2
  inputs:
    testRunner: xUnit
    testResultsFiles: '**/*.trx'
    failTaskOnFailedTests: true