trigger:
  - master

pool:
  vmImage: 'windows-2019'

steps:

- task: gittools.gitversion.gitversion-task.GitVersion@4
  inputs:
    preferBundledVersion: false
  displayName: Determine Semantic Version

- powershell: |
    dotnet publish src/Artifacts/Artifacts.csproj `
      --output $(build.artifactStagingDirectory) `
      -p:Version=$(GitVersion.AssemblySemVer)
  displayName: dotnet publish

- task: PublishBuildArtifacts@1
