trigger:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    dotnet publish src/Artifacts/Artifacts.csproj \
      --output $(build.artifactStagingDirectory)
  displayName: dotnet publish

- task: PublishBuildArtifacts@1
